server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service # 应用名称

mybatis:
  type-aliases-package: com.yueguoo.mybatis.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

mappe:
   mappers: com.yueguoo.mybatis.mappers.MyMapper
   identity: MYSQL

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka,http://127.0.0.1:10088/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${server.port}

