server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service # 应用名称
mybatis:
  type-aliases-package: com.yueguoo.mybatis.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
mappe:
  mappers: com.yueguoo.mybatis.mappers.MyMapper
  identity: MYSQL
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka,http://127.0.0.1:10088/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找



    #DB Configuration:
#    spring.datasource.driverClassName=com.mysql.jdbc.Driver
#    spring.datasource.url=
#    spring.datasource.username=root
#    spring.datasource.password=
    #spring集成Mybatis环境


    #mybatis&&通用Mapper
    #pojo别名扫描包
#    mybatis.type-aliases-package=
#    #加载Mybatis映射文件
#    mybatis.mapper-locations=classpath:mapper/*Mapper.xml
#    mapper.mappers=com.yueguoo.mybatis.mappers.MyMapper
#    mapper.identity=MYSQL
#
#    #分页插件
#    pagehelper.helperDialect=mysql
#    pagehelper.reasonable=true
#    pagehelper.supportMethodsArguments=true
#    pagehelper.params=count=countSql
#
#    #log
#    logging.file=logger.log
#    logging.level.*=debug
